# ===============================
# = Spring configurations
# ===============================
spring:
  name: local
  # = HTTP requests configurations ##############################
  servlet:
    multipart:
      location: /tmp
  datasource:
    url:      ${env.SPRING_DATASOURCE_URL}
    username: ${env.SPRING_DATASOURCE_USERNAME}
    password: ${env.SPRING_DATASOURCE_PASSWORD}
docker:
  host: ${env.DOCKER.URL}
  tls-verify: false
  cert-path: ${env.DOCKER.CERT_PATH}